/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Frébault
 */
public class EntreeEnStock extends javax.swing.JFrame {

    /**
     * Creates new form EntreeEnStock
     */
    public EntreeEnStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TbxCodeBarre = new javax.swing.JTextField();
        CalAchat = new com.toedter.calendar.JCalendar();
        LabelCodeBarre = new javax.swing.JLabel();
        CalPeremption = new com.toedter.calendar.JCalendar();
        LabelPeremption = new javax.swing.JLabel();
        LabelAchat = new javax.swing.JLabel();
        LabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setName("container"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TbxCodeBarre.setToolTipText("Scannez le Code Barre");
        TbxCodeBarre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TbxCodeBarreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TbxCodeBarreKeyTyped(evt);
            }
        });

        CalAchat.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N

        LabelCodeBarre.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        LabelCodeBarre.setText("Code Barre");

        CalPeremption.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N

        LabelPeremption.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        LabelPeremption.setText("Date de péremption");

        LabelAchat.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        LabelAchat.setText("Date d'achat");

        LabelResult.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        LabelResult.setMaximumSize(new java.awt.Dimension(50, 20));
        LabelResult.setMinimumSize(new java.awt.Dimension(50, 20));
        LabelResult.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalAchat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalPeremption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPeremption, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCodeBarre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TbxCodeBarre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPeremption, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalPeremption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TbxCodeBarre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCodeBarre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void TbxCodeBarreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbxCodeBarreKeyTyped
        // TODO add your handling code here:
        if(TbxCodeBarre.getText().length()>=13)
        {    evt.consume(); }

    }//GEN-LAST:event_TbxCodeBarreKeyTyped

    private void TbxCodeBarreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbxCodeBarreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            
        }
    }//GEN-LAST:event_TbxCodeBarreKeyPressed
    
    private int calculeCodeBarre(String codebarre12){
        
            int code1=Integer.parseInt(codebarre12.substring(0, 1));
            int code2=Integer.parseInt(codebarre12.substring(1, 1));
            int code3=Integer.parseInt(codebarre12.substring(2, 1));
            int code4=Integer.parseInt(codebarre12.substring(3, 1));
            int code5=Integer.parseInt(codebarre12.substring(4, 1));
            int code6=Integer.parseInt(codebarre12.substring(5, 1));
            int code7=Integer.parseInt(codebarre12.substring(6, 1));
            int code8=Integer.parseInt(codebarre12.substring(7, 1));
            int code9=Integer.parseInt(codebarre12.substring(8, 1));
            int code10=Integer.parseInt(codebarre12.substring(9, 1));
            int code11=Integer.parseInt(codebarre12.substring(10, 1));
            int code12=Integer.parseInt(codebarre12.substring(11, 1));
            
            int s1 = code1+code2*3+code3+code4*3+code5+code6*3+code7+code8*3+code9+code10*3+code11+code12*3;
            int digite = 10 - (s1%10);
            
            String codebarre13= codebarre12;//+ digite.toString();
        
        return Integer.parseInt(codebarre13);
    }
    
                              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntreeEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntreeEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntreeEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntreeEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntreeEnStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar CalAchat;
    private com.toedter.calendar.JCalendar CalPeremption;
    private javax.swing.JLabel LabelAchat;
    private javax.swing.JLabel LabelCodeBarre;
    private javax.swing.JLabel LabelPeremption;
    private javax.swing.JLabel LabelResult;
    private javax.swing.JTextField TbxCodeBarre;
    // End of variables declaration//GEN-END:variables
}
